export const tableConfig = [
  {
    field: "complaintNumber",
    header: "Complaint Number",
    filter: true,
    filterMatchMode: "contains",
    sortable: true,
  },
  {
    field: "complaintDepartment",
    header: "Complaint Department",
    filter: true,
    filterMatchMode: "contains",
    sortable: true,
  },
  {
    field: "complaintStatus",
    header: "Complaint Status",
    filter: true,
    filterMatchMode: "contains",
    sortable: true,
  },
  {
    field: "complaintDate",
    header: "Complaint Date",
    filter: true,
    filterMatchMode: "contains",
    sortable: true,
  },
  {
    field: "taxpayerName",
    header: "Taxpayer Name",
    filter: true,
    filterMatchMode: "contains",
    sortable: true,
  },
  {
    field: "city",
    header: "City",
    filter: true,
    filterMatchMode: "contains",
    sortable: true,
  },
  {
    field: "area",
    header: "Area",
    filter: true,
    filterMatchMode: "contains",
    sortable: true,
  },
  {
    field: "taxpayerBranchName",
    header: "Taxpayer Branch Name",
    filter: true,
    filterMatchMode: "contains",
    sortable: true,
  },
  {
    field: "RIN",
    header: "RIN",
    filter: true,
    filterMatchMode: "contains",
    sortable: true,
  },
  {
    field: "incentiveRegistered",
    header: "Incentive Registered",
    filter: true,
    filterMatchMode: "contains",
    sortable: true,
  },
  {
    field: "taxpayerType",
    header: "Taxpayer Type",
    filter: true,
    filterMatchMode: "contains",
    sortable: true,
  },
  {
    field: "complaintType",
    header: "Complaint Type",
    filter: true,
    filterMatchMode: "contains",
    sortable: true,
  },
  {
    field: "customerName",
    header: "Customer Name",
    filter: true,
    filterMatchMode: "contains",
    sortable: true,
  },
  {
    field: "customerMobile",
    header: "Customer Mobile",
    filter: true,
    filterMatchMode: "contains",
    sortable: false,
  },
  {
    field: "customerNationalID",
    header: "Customer National ID",
    filter: true,
    filterMatchMode: "contains",
    sortable: false,
  },
];
